security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        users_in_memory:
            memory:
                users:
                    # admin: { password: 'admin123', roles: ['ROLE_ADMIN'] }
                    # user: { password: 'user123', roles: ['ROLE_USER'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/kontakt
            http_basic: ~
            provider: users_in_memory
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\KontaktyAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/o-nas, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon