<?php

namespace ContainerItP7zwA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKontaktRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\KontaktRepository' shared autowired service.
     *
     * @return \App\Repository\KontaktRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\KontaktRepository'] = new \App\Repository\KontaktRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
